services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    env_file:
      - .env
    image: jetshift:dev
    container_name: jetshift
    ports:
      - "${APP_PORT:-8000}:8000"
      - "${PREFECT_PORT:-4200}:4200"
    environment:
      APP_PORT: ${APP_PORT:-8000}
      PREFECT_PORT: ${PREFECT_PORT:-4200}
    volumes:
      - .:/app:delegated
    depends_on:
      - redis
      - postgres
    networks:
      - default

#  jsui:
#    image: jetshift/jetshift-ui:dev
#    container_name: jetshift_ui
#    environment:
#      NEXT_PUBLIC_API_BASE_URL: http://jetshift:8000/api
#      NEXT_PUBLIC_WS_URL: ws://jetshift:8000/ws/
#      NEXT_PUBLIC_PREFECT_URL: http://jetshift:4200
#    ports:
#      - "4000:3000"
#    networks:
#      - default
#    depends_on:
#      - app

  redis:
    image: redis:7-alpine
    container_name: jetshift_redis
    ports:
      - "6379:6379"
    networks:
      - default

  postgres:
    image: postgres:15-alpine
    container_name: jetshift_postgres
    environment:
      POSTGRES_DB: jetshift
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
