# Generated by Django 5.1.5 on 2025-01-23 20:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialect', models.CharField(choices=[('sqlite', 'SQLite'), ('mysql', 'MySQL'), ('postgres', 'PostgreSQL')], max_length=50)),
                ('type', models.CharField(choices=[('source', 'Source'), ('target', 'Target')], max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('host', models.CharField(blank=True, max_length=191, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('password', models.CharField(blank=True, max_length=191, null=True)),
                ('database', models.CharField(blank=True, max_length=191, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'js_databases',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'js_users',
            },
        ),
        migrations.CreateModel(
            name='MigrateDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('status', models.IntegerField(default=0)),
                ('logs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_migrations', to='api.database')),
                ('target_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_migrations', to='api.database')),
            ],
            options={
                'db_table': 'js_migrate_databases',
            },
        ),
        migrations.CreateModel(
            name='MigrateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('source_tables', models.TextField(blank=True, null=True)),
                ('target_tables', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('logs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_table_jobs', to='api.database')),
                ('target_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_table_jobs', to='api.database')),
            ],
            options={
                'db_table': 'js_migrate_tables',
            },
        ),
    ]
