# Generated by Django 5.1.7 on 2025-03-29 09:02

import app.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialect', models.CharField(choices=[('sqlite', 'SQLite'), ('mysql', 'MySQL'), ('postgres', 'PostgreSQL')], max_length=50)),
                ('type', models.CharField(choices=[('source', 'Source'), ('target', 'Target')], max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('host', models.CharField(blank=True, max_length=191, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('password', models.CharField(blank=True, max_length=191, null=True)),
                ('database', models.CharField(blank=True, max_length=191, null=True)),
                ('secure', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'js_databases',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'js_users',
            },
        ),
        migrations.CreateModel(
            name='MigrateDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('migrating', 'Migrating'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('logs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_migrations', to='app.database')),
                ('target_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_migrations', to='app.database')),
            ],
            options={
                'db_table': 'js_migrate_databases',
            },
        ),
        migrations.CreateModel(
            name='MigrateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('migrating', 'Migrating'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('logs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_table_jobs', to='app.database')),
                ('target_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_table_jobs', to='app.database')),
            ],
            options={
                'db_table': 'js_migrate_tables',
            },
        ),
        migrations.CreateModel(
            name='MigrationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table', models.CharField(max_length=255)),
                ('target_table', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('migrating', 'Migrating'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('config', models.JSONField(default=app.models.default_migration_task_config)),
                ('stats', models.JSONField(default=app.models.default_migration_task_stats)),
                ('deployment_id', models.CharField(max_length=255)),
                ('error', models.TextField(blank=True, default='')),
                ('migrate_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.migratetable')),
            ],
            options={
                'db_table': 'js_migrate_table_tasks',
            },
        ),
    ]
