# Generated by Django 5.1.7 on 2025-03-20 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migratedatabase',
            name='source_db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_migrations', to='app.database'),
        ),
        migrations.AlterField(
            model_name='migratedatabase',
            name='target_db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_migrations', to='app.database'),
        ),
        migrations.AlterField(
            model_name='migratetable',
            name='source_db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_table_jobs', to='app.database'),
        ),
        migrations.AlterField(
            model_name='migratetable',
            name='target_db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_table_jobs', to='app.database'),
        ),
    ]
